apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
stringData:
  # Encryption key for credentials (do not change after initial deployment)
  N8N_ENCRYPTION_KEY: "c5c2cf59df19640c10c21ba1b0f434863bbbf6a688392e65ad9cf910eac0605b"
  
  # Basic auth for webhook endpoints (optional but recommended)
  N8N_BASIC_AUTH_USER: "admin"
  N8N_BASIC_AUTH_PASSWORD: "n8n-webhook-secure-2024"
