# Prometheus + Grafana Monitoring Stack
# Uses the kube-prometheus-stack Helm chart via ArgoCD

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  
  source:
    # Using Helm chart from prometheus-community
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1  # Latest stable version
    
    helm:
      values: |
        # Grafana configuration
        grafana:
          enabled: true
          adminPassword: "admin123"  # Change this!
          service:
            type: LoadBalancer
          persistence:
            enabled: false  # Enable for production
          
          # Additional dashboards from grafana.com
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'grafana-dashboards'
                orgId: 1
                folder: 'Community'
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/grafana-dashboards
                  
          dashboards:
            grafana-dashboards:
              # Node Exporter Full - works great with K3S
              node-exporter-full:
                gnetId: 1860
                revision: 37
                datasource: Prometheus
              # Kubernetes / Compute Resources / Cluster (built into kube-prometheus)
              # Already included by default - no need to import
          
        # Prometheus configuration  
        prometheus:
          prometheusSpec:
            retention: 7d  # Keep 7 days of data
            resources:
              requests:
                memory: 400Mi
                cpu: 200m
              limits:
                memory: 1Gi
                cpu: 1000m
            storageSpec: {}  # Add persistent storage for production
          service:
            type: LoadBalancer
            
        # Alertmanager configuration
        alertmanager:
          enabled: true
          alertmanagerSpec:
            resources:
              requests:
                memory: 64Mi
                cpu: 50m
              limits:
                memory: 128Mi
                cpu: 100m
          service:
            type: ClusterIP
            
        # Node exporter - metrics from nodes
        nodeExporter:
          enabled: true
          
        # Kube-state-metrics - metrics from K8s objects
        kubeStateMetrics:
          enabled: true
          
        # Reduce resource usage for home lab
        prometheusOperator:
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
